<?php

declare(strict_types=1);

return [
    'version' => 1,
    'owner' => 'application',
    'agents' => [
        'opus.central' => [
            'mode' => 'central',
            'description' => 'Coordinates application tasks through a bounded command surface.',
            'profile' => 'opus.central',
            'tools' => [
                'command.list',
                'command.get',
                'command.help',
                'feature.list',
                'feature.show',
                'feature.more',
                'feature.help',
                'info.get',
                'info.help',
                'calc.do',
                'calc.help',
                'howto.find',
                'howto.show',
                'howto.help',
                'resource.list',
                'resource.show',
                'resource.more',
                'resource.help',
                'todo.list',
                'todo.open',
                'todo.select',
                'todo.find',
                'todo.previous',
                'todo.next',
                'todo.help',
                'todo.make',
                'todo.add',
                'todo.edit',
                'todo.delete',
                'note.list',
                'note.get',
                'note.find',
                'note.next',
                'note.previous',
                'note.help',
                'note.make',
                'note.save',
                'schedule.list',
                'schedule.next',
                'schedule.previous',
                'schedule.help',
                'schedule.add',
                'schedule.edit',
                'schedule.delete',
                'step.list',
                'step.show',
                'step.get',
                'step.previous',
                'step.next',
                'step.help',
                'step.generate',
                'step.update',
                'step.set',
                'step.add',
                'step.delete',
            ],
            'imports' => [],
            'exports' => [],
            'permissions' => [],
            'lifecycle' => [
                'states' => ['active'],
            ],
        ],
    ],
];
