services:
  nginx:
    image: nginx:alpine
    ports:
      - "${BF_HTTP_PORT:-8080}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks: [bf]

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        INSTALL_XDEBUG: ${BF_INSTALL_XDEBUG:-false}
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro
    environment:
      APP_ENV: local
      PHP_IDE_CONFIG: "serverName=bf-local"
      MYSQL_DB_HOST: ${BF_MYSQL_DB_HOST:-mysql}
      MYSQL_DB_PORT: ${BF_MYSQL_DB_PORT:-3306}
      MYSQL_DB_NAME: ${BF_MYSQL_DB_NAME:-app}
      MYSQL_DB_USERNAME: ${BF_MYSQL_DB_USERNAME:-root}
      MYSQL_DB_PASSWORD: ${BF_MYSQL_DB_PASSWORD:-root}
    networks: [bf]
